dwim-coder-mode is a Rube Goldberg machine mode for GNU Emacs.  dwim-coder-mode helps you
code/go crazy.  Currently good support for C, Python and Rust programming are included.

dwim-coder-mode requires ~electric-pair-mode~ to work.  Since dwim-coder-mode is based on treesitter,
dwim-coder-mode requires GNU Emacs 30+ to work.

Source Repository: [[https://gitlab.com/sadiq/dwim-coder-mode][GitLab]], [[https://sr.ht/~sadiq/dwim-coder-mode/][SourceHut]]

Issues and Feature Requests: [[https://gitlab.com/sadiq/dwim-coder-mode/-/issues][GitLab]]

Homepage: [[https://www.sadiqpk.org/projects/dwim-coder-mode.html][https://www.sadiqpk.org/projects/dwim-coder-mode.html]]

* Introduction
  dwim-coder-mode hacks around the characters you type to do various stuff often
  reducing the effort to accomplish something.

  Say for example, in c-ts-mode, pressing space bar often inserts '_' or sometimes
  real spaces depending on the context. It also inserts '-' when inside #include
  header names.  And S-SPC inserts real space too.

* But why?
  Why not? This is GNU Emacs, anything is possible ;).

  I have been using this for more than a decade in my personal config, and I decided
  to create a mode doing the same.

  And it's great to have something cool to show off about your editor, right?

* Installation

** Installing from git
   #+begin_src sh
   emacs --batch --eval='(package-vc-install "https://gitlab.com/sadiq/dwim-coder-mode")'
   #+end_src

** Configuration

  #+BEGIN_SRC emacs-lisp
    (use-package dwim-coder-mode
      :hook ((c-ts-mode python-ts-mode rust-ts-mode) . dwim-coder-mode))

  #+END_SRC
